repos:
- repo: local
  hooks:
  - id: cargo-fmt
    name: cargo fmt
    entry: cargo fmt -- --check
    language: system
    types: [rust]
    pass_filenames: false
  - id: cargo-clippy
    name: cargo clippy (pedantic)
    entry: cargo clippy --all-targets --all-features -- -W clippy::pedantic -D warnings
    language: system
    types: [rust]
    pass_filenames: false
  - id: cargo-test
    name: cargo test
    entry: cargo test
    language: system
    types: [rust]
    pass_filenames: false
